/*
 * Auto-generated by `mifl-migrator sync-preview`.
 * Do not edit manually.
 */

import type { ScreenModuleLoader } from "../manifest/types";

export const generatedScreenModuleLoaders: Record<string, ScreenModuleLoader> = {
};
